language: node_js
node_js: '8'
notifications:
  email: false

before_install:
  - rvm install 2.4
  - rvm use 2.
  - gem install bundler
  - bundle install

install:
  - npm install -g firebase-tools

script: bundle exec jekyll build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --only hosting
branches:
  only:
  - master
sudo: false