title: Code for Heilbronn e.V.
description: >-
  Offene Werkstatt - Open Data - Software- und Hardware Workshops

permalink: /:title.html
logo: /uploads/CodeForHeilbronn.svg
lang: de-DE
timezone: Europe/Berlin
avatarurl: /favicon.png

remote_theme: daviddarnes/alembic

markdown: kramdown

collections:
  uploads:
    title: Uploads
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projekte
    output: true
  badges:
    title: Badges
    output: true
  events:
    title: Events
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: /:year/:month/:day/:title.html

navigation_header:
  Blog: /
  Verein: /verein/
  Badges: /badges/
  Projekte: /projects/
  Termine: /events/
  Über: /about/

navigation_footer:
  Kategorien: /categories
  Satzung: /satzung
  Mitgliedsantrag: /uploads/Mitgliedsantrag.pdf

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
   - Gemfile
   - Gemfile.lock
   - .idea/